### ISSUE TITLE
No handlers could be found for logger "ws4py"

### ISSUE THREAD

**Issue by ribeirocctv** [FeLiNa22/amazon-alexa-lg-tv#14]
After I say YES on the TV I got the error

$ sudo python setup.py
timed out
timed out
timed out
timed out
{
    "count": 0, 
    "result": "failed"
}
Enter IP of TV : '192.168.1.68'
No handlers could be found for logger "ws4py"
{"closing": {"reason": "Going away", "code": 1006}}
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    lgtv.LGparser(['listChannels'])
  File "/home/ribeiro/amazon-alexa-lg-tv-master/lgtv.py", line 113, in LGparser
    ws.connect()
  File "/home/ribeiro/.local/lib/python2.7/site-packages/ws4py/client/__init__.py", line 217, in connect
    self.sock.connect(self.bind_addr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
$

**Comment by ribeirocctv** [comment]
Already resolved.
I was using a vm with nat. change to bridge and everything works.
thanks a lot
